name: Update FPL Data
on:
  schedule:
    - cron: '0 */3 * * *'  # ၃ နာရီပြည့်တိုင်း (တစ်နေ့ ၈ ကြိမ်) အလိုလို Run မည်
  workflow_dispatch:      # Actions tab ထဲတွင် Manual Run ခလုတ် ပေါ်စေရန်

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch Data
        run: curl "https://fantasy.premierleague.com/api/bootstrap-static/" -o data.json
        
      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Auto Update [skip ci]" || exit 0
          git push
