name: Update FPL Data
on:
  schedule:
    - cron: '*/15 * * * *' # ၁၅ မိနစ်တစ်ခါ အလိုအလျောက် Update လုပ်မည်
  workflow_dispatch: # ကိုယ်တိုင်နှိပ်ပြီး Run ချင်လျှင်လည်း ရသည်

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # GitHub ထဲ ပြန်ရေးဖို့ ခွင့်ပြုချက်
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch FPL Data
        run: |
          curl "https://fantasy.premierleague.com/api/bootstrap-static/" -o data.json

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          # [skip ci] ပါမှ Loop မပတ်မှာ ဖြစ်ပါတယ်
          git commit -m "Auto Update FPL Data [skip ci]" || exit 0
          git push
